spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/ProductsAPIDB
    driverClassName: org.h2.Driver
    username: seuusuario
    password: suasenha

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true